#!/usr/bin/env sh

#TODO: Improve script logic

./font-patcher --careful --windows --custom codicons ../HackNFCLigaturedCCG-Regular.ttf
./font-patcher --careful --windows --custom codicons ../HackNFCLigaturedCCG-Italic.ttf
./font-patcher --careful --windows --custom codicons ../HackNFCLigaturedCCG-Bold.ttf
./font-patcher --careful --windows --custom codicons ../HackNFCLigaturedCCG-BoldItalic.ttf

